### ISSUE TITLE
wt=javabin not working 

### ISSUE THREAD

**Issue by LimAyo** [tflobbe/solrmeter#123]
hello : @tflobbe  
when i configure my solrMeter this crach raise : 
Illegal character in scheme name at index 0 : 
127.0.0.1:8983/solr/Product/select?q=%22*%22&wt=javabin&indent=true&version=2 
i copied the url in the browser , it doesn't work 
when i replace  "wt=javabin" by ( wt=xml or wt=json  ) , 
is there a configuration to remove or replce the wt ?
please i have to make this Tool working on my project :100:

**Comment by tflobbe** [comment]
Maybe you can paste the stacktrace from Solr. The "wt=javabin" is correct since that's that SolrJ uses. It also makes sense that this won't work from your browser since it's binary format.

**Comment by LimAyo** [comment]
well i did not pay attention to the Url , i forgot to add http and the url was not correct ,
i will close the issue
