### ISSUE TITLE
Links to sample files broken

### ISSUE THREAD

**Issue by GrayedFox** [tflobbe/solrmeter#124]
The links to the sample query, params, fields, etc files are broken.

Would be helpful for rookies like myself looking to learn :+1: 

I.e. check [this][1] wiki page and click on the "example file" link

[1]: https://github.com/tflobbe/solrmeter/blob/wiki/queries.md

**Comment by tflobbe** [comment]
I fixed most of the links, I hope it helps. Images are still broken. (It looks like they were not migrated from google code)

**Comment by GrayedFox** [comment]
Thanks tflobbe, will close :+1:
